### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/searchpress#105]
As of PHP7.2, this will trigger a warning. This may be low-priority since this seems to only run on a cron job. At any rate, this should probably be updated.

`Method name "Searchpress_CLI_Command::__apply_date_range" is discouraged; PHP has reserved all method names with a double underscore prefix for future use.`

https://github.com/alleyinteractive/searchpress/blob/9755c9bd6185e7d0cf2680523e0206073644343b/bin/wp-cli.php#L94

**Comment by renatonascalves** [comment]
PHP 7.2 is no longer supported! Closing as invalid.
