### ISSUE TITLE
Documentation: difference to ElasticPress?

### ISSUE THREAD

**Issue by lkraav** [alleyinteractive/searchpress#127]
Hi. AFAICT these might be the top 2 dogs in WP ElasticPress integration space.

But what's the difference. How should a user choose?

**Comment by mboynes** [comment]
Hey @lkraav, thanks for the question. To be perfectly honest, I've never used ElasticPress and I don't think any of the maintainers of SearchPress would be well-suited to objectively compare and contrast the two. I encourage you to try both out and blog about your experience! Perhaps you'll be able to answer that question for others wondering the same. If you decide to do that and there's anything about SearchPress specifically that I can answer for you, I'm happy to do so. Please don't hesitate to reach out!
