### ISSUE TITLE
PHP 7.4 Compatibility

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/searchpress#143]
An issue to collect problems with PHP 7.4 and the current codebase.

* Warning in `bin/wp-cli.php`: Method name `Searchpress_CLI_Command::__apply_date_range` is discouraged; PHP has reserved all method names with a double underscore prefix for future use.

**Comment by renatonascalves** [comment]
This looks like a duplicate of #105, which already has a pull request.

**Comment by mogmarsh** [comment]
handled by https://github.com/alleyinteractive/searchpress/commit/14b34ee531b04efd119c109e4faff409319fc002
