### ISSUE TITLE
Separate indexable vs. searchable post types

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/searchpress#16]
- [ ] Indexing should use `SP_Config::sync_post_types()` to define the indexed post types
- [ ] SP should index all post types so it's not limited to being used just across searchable post types
- [ ] Ensure that the above updates don't affect the post types used when searching

**Comment by gibrown** [comment]
This is probably a distraction, but want to look at wpes-lib again (https://github.com/Automattic/wpes-lib)? All post types, post statuses, attachments, comments, etc. We've already got code that handles all of these cases: 

https://github.com/Automattic/wpes-lib/blob/master/src/common/class.wpes-wp-post-field-builder.php#L705

Happy to provide all the code for real time indexing triggers and all the api calls that wrap this stuff as examples if that helps. Our index management code and async jobs are too heavily embedded for it to be directly usable, but there is a lot of useful code there. (eg I'm just getting real time indexing of attachments working when parent docs get updated.)

Our php API:
```
function es_api_search_index( $args, $stat_app_name = 'unknown' )
function es_api_count_docs( $args, $stat_app_name = 'unknown' )
function es_api_search_index_for_related( $args, $stat_app_name = 'unknown' )
function wpcom_search_api_query( $args, $stat_app_name = 'blog-search' )
function es_api_is_item_in_index( $args )
function es_api_get_item( $args )
function es_api_detect_lang( $text, $force_detect = false, $retries = 0 )
function es_langdetect_by_chars( $text, $unicode_regex, $percentage )
function es_api_word_count( $text, $lang = false )
function es_api_analyze_text( $text, $lang = false )
//   For this function the app name will be prefixed with 'classify-'
function es_api_classify_doc( $args, $stat_app_name = 'unknown' )
function wpcom_search_api_wp_to_es_args( $args )
function es_api_parse_user_query( $args )
function es_api_bulk_index_blog_to_index( $args )
function es_api_bulk_index_comments_by_post( $args )
function es_api_bulk_index( $args )
function es_api_bulk_delete( $args )
function es_api_bulk_clean_blog( $args )
function es_api_bulk_check_blog( $args )
function es_api_index_changed_wp_comment( $args )
function es_api_index_changed_wp_post( $args )
function es_api_index_changed_item( $args )
function es_api_index_changed_items( $args )
function es_api_index_changed_wp_post_bulk( $args )
function es_api_index_changed_wp_blog_term( $args )
function es_api_index_changed_wp_blog( $args )
function es_api_index_item( $args )
function es_api_delete_item( $args )
function es_api_update_item( $args )
```
