### ISSUE TITLE
Add setting or filter for admin-based bulk indexing.

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/searchpress#52]
On sites with complex post types, the admin-based indexer times out while processing posts in batches of 500. The ability to filter or otherwise adjust that value would make indexing via admin more reliable, which would be particularly useful for environments where WP CLI isn't available or where commands must be run by the web host's staff.

**Comment by mboynes** [comment]
In SearchPress, everything is modifiable. Filters are used where that is the most appropriate, and class methods are used elsewhere. In this case, there's a magic method that allows you to set the bulk quantity, which you can set using e.g. `SP_Sync_Meta()->bulk = 100;`

**Comment by scottnelle** [comment]
http://www.reactiongifs.us/wp-content/uploads/2014/06/sheepish_aladdin.gif

Thanks @mboynes!

**Comment by mboynes** [comment]
np!
